language: node_js
node_js:
 - "node"

cache: npm

script: npm run build

deploy:
 provider: pages
 skip_cleanup: true
 github_token: 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
 local_dir: dist
 on:
   branch: master